#!/bin/bash

echo "🚀 FinanceAI Deployment Setup"
echo "=============================="

echo ""
echo "📋 Prerequisites Checklist:"
echo "1. GitHub repository: ✅ (Already configured)"
echo "2. Netlify account needed"
echo "3. Cloudflare account needed"
echo "4. API keys for Plaid, Chase, Anthropic"

echo ""
echo "🔧 Next Steps:"
echo ""
echo "1. Set up GitHub Secrets:"
echo "   Go to: https://github.com/Aisprintone/Sparrow/settings/secrets/actions"
echo ""
echo "2. Add these secrets:"
echo "   - NETLIFY_AUTH_TOKEN"
echo "   - NETLIFY_SITE_ID"
echo "   - CLOUDFLARE_API_TOKEN"
echo "   - CLOUDFLARE_ACCOUNT_ID"
echo "   - NEXT_PUBLIC_API_URL"
echo "   - PLAID_CLIENT_ID"
echo "   - PLAID_CLIENT_SECRET"
echo "   - CHASE_API_KEY"
echo "   - ANTHROPIC_API_KEY"
echo ""
echo "3. Enable GitHub Actions:"
echo "   Go to: https://github.com/Aisprintone/Sparrow/actions"
echo ""
echo "4. Create Netlify site:"
echo "   - Connect your GitHub repository"
echo "   - Set build command: cd frontend && npm run build"
echo "   - Set publish directory: frontend/out"
echo ""
echo "5. Create Cloudflare Workers:"
echo "   - Deploy from cloudflare-workers/financeai-backend"
echo "   - Update wrangler.jsonc with your KV namespace IDs"
echo ""
echo "📖 Full deployment guide: DEPLOYMENT_GUIDE.md"
echo ""
echo "✅ Ready to deploy!"
