/**
 * AI Insights Service - Frontend Integration
 * Consumes AI insights generated by the backend RAG system
 */

import { apiClient } from './client';

export interface AIInsight {
  type: 'financial_analysis' | 'spending_pattern' | 'investment_recommendation' | 'risk_assessment';
  title: string;
  content: string;
  confidence: number;
  timestamp: string;
}

export interface SimulationInsight {
  scenario_type: string;
  insights: AIInsight[];
  recommendations: string[];
  risk_factors: string[];
}

export class AIInsightsService {
  /**
   * Get AI-generated financial insights for a profile
   */
  async getFinancialInsights(profileId: number): Promise<AIInsight[]> {
    try {
      const response = await apiClient.post<{ insights: AIInsight[] }>(
        `/ai/generate-explanations`,
        {
          profile_id: profileId,
          insight_type: 'financial_analysis'
        }
      );
      return response.insights || [];
    } catch (error) {
      console.error('[AI INSIGHTS] Failed to get financial insights:', error);
      return [];
    }
  }

  /**
   * Get AI-generated spending analysis
   */
  async getSpendingAnalysis(profileId: number): Promise<AIInsight[]> {
    try {
      const response = await apiClient.post<{ insights: AIInsight[] }>(
        `/ai/generate-explanations`,
        {
          profile_id: profileId,
          insight_type: 'spending_pattern'
        }
      );
      return response.insights || [];
    } catch (error) {
      console.error('[AI INSIGHTS] Failed to get spending analysis:', error);
      return [];
    }
  }

  /**
   * Get AI-generated investment recommendations
   */
  async getInvestmentRecommendations(profileId: number): Promise<AIInsight[]> {
    try {
      const response = await apiClient.post<{ insights: AIInsight[] }>(
        `/ai/generate-explanations`,
        {
          profile_id: profileId,
          insight_type: 'investment_recommendation'
        }
      );
      return response.insights || [];
    } catch (error) {
      console.error('[AI INSIGHTS] Failed to get investment recommendations:', error);
      return [];
    }
  }

  /**
   * Get simulation-specific insights
   */
  async getSimulationInsights(simulationId: string): Promise<SimulationInsight | null> {
    try {
      const response = await apiClient.get<SimulationInsight>(
        `/simulation/${simulationId}/insights`
      );
      return response;
    } catch (error) {
      console.error('[AI INSIGHTS] Failed to get simulation insights:', error);
      return null;
    }
  }

  /**
   * Get personalized financial advice
   */
  async getPersonalizedAdvice(profileId: number): Promise<string> {
    try {
      const response = await apiClient.post<{ advice: string }>(
        `/ai/generate-explanations`,
        {
          profile_id: profileId,
          insight_type: 'personalized_advice'
        }
      );
      return response.advice || 'Unable to generate personalized advice at this time.';
    } catch (error) {
      console.error('[AI INSIGHTS] Failed to get personalized advice:', error);
      return 'Unable to generate personalized advice at this time.';
    }
  }
}

// Export singleton instance
export const aiInsightsService = new AIInsightsService();
