name: Deploy to Railway

on:
  push:
    branches: [main, develop]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-railway.yml'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.11'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Install Railway CLI
        run: npm install -g @railway/cli
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/python_engine/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
          
      - name: Install Python dependencies
        run: |
          cd backend/python_engine
          pip install -r requirements.txt
          
      - name: Copy CSV data files
        run: |
          cd backend/python_engine
          mkdir -p data
          cp ../../data/*.csv data/ 2>/dev/null || echo "⚠️ Some CSV files not found, will use mock data"
          
      - name: Test Python backend
        run: |
          cd backend/python_engine
          python -c "import api.main; print('✅ Python backend modules loaded successfully')"
        env:
          PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
          PLAID_CLIENT_SECRET: ${{ secrets.PLAID_CLIENT_SECRET }}
          CHASE_API_KEY: ${{ secrets.CHASE_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          
      - name: Deploy to Railway
        run: |
          cd backend/python_engine
          railway up --service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          
      - name: Verify Railway deployment
        run: |
          echo "✅ Railway deployment completed"
          echo "🔗 Railway URL: https://sparrow-backend-production.up.railway.app"
          sleep 30
          curl -f https://sparrow-backend-production.up.railway.app/health || echo "⚠️ Health check failed, but deployment may still be processing"
